config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :employees
  resources :leave_requests
  resources :attendences
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "employees#index"
  post 'update_status' => 'leave_requests#update_status'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendence.rb
class Attendence < ApplicationRecord
  belongs_to :employee
end

app/models/employee.rb
class Employee < ApplicationRecord
   
end

app/models/leave_request.rb
class LeaveRequest < ApplicationRecord
    belongs_to :employee
    enum status: { pending: 0, approved: 1, rejected: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendences_controller.rb
class AttendencesController < ApplicationController
  before_action :find_employee_attendence, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @attendence = Attendence.all
  end

  def show; end 

  def new
    @employees = Employee.all
    @attendence = Attendence.new
  end

  def create
    @attendence = Attendence.new(attendence_params)
    if @attendence.save
      flash[:notice] = 'Attendence of employee is created'
      redirect_to attendences_path
    else
      render :new
    end
  end

  def edit
    @employees = Employee.all
    end

  def update
    if @attendence.update(attendence_params)
      redirect_to attendences_path, notice: 'Attendence is sucessfully updated'
    else
      render :edit
    end
  end

  def destroy
    @attendence.destroy
    redirect_to attendence_path, notice: 'Attendence is sucessfully destroyed'
  end

  private

  def find_employee_attendence
    @attendence = Attendence.find(params[:id])
  end

  def attendence_params
    params.require(:attendence).permit(:check_in_time, :check_out_time, :date, :employee_id)
  end
end 

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    before_action :find_employee, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!

    def index
        @employee = Employee.all
    end

    def show
      
    end

    def new
        @employee = Employee.new
    end

    def create
        @employee =  Employee.new(employee_params)
        if @employee.save
            flash[:notice] = 'Employee was sucessfully created'
            redirect_to employees_path
        else 
            render :new
        end
    end

    def edit

    end

    def update
        if @employee.update(employee_params)
            redirect_to employees_path, notice: 'Employee was sucessfully updated'
        else
            render :edit
        end
    end

    def destroy
      
        @employee.destroy
        redirect_to employees_path, notice: 'Employee was sucessfully destroyed'
    end

    private 

    def find_employee
        @employee = Employee.find(params[:id])
    end

    def employee_params
        params.require(:employee).permit(:first_name, :last_name, :email, :phone_num, :hire_date, :job_title, :department)
    end
end

app/controllers/leave_requests_controller.rb
class LeaveRequestsController < ApplicationController
  before_action :find_employee_leave_request, only: %i[show edit update destroy]
  before_action :all_employees, only: %i[new edit]
  before_action :authenticate_user!

  def index
    @leave_request = LeaveRequest.all
  end

  def show; end

  def new
    @leave_request = LeaveRequest.new
  end

  def create
    @leave_request = LeaveRequest.new(leave_params)
    if @leave_request.save
      flash[:notice] = 'Leave request was sucessfully created'
      redirect_to leave_requests_path
    else
      render :new
    end
  end

  def edit

  end
   

  def update
    if @leave_request.update(leave_params)
      redirect_to leave_requests_path, notice: 'Leave request was sucessfully created'

    else
      render :edit
    end
  end

  def destroy
    @leave_request.destroy
    redirect_to leave_requests_path
  end

  def update_status
    leave_request = LeaveRequest.find(params['format'].to_i)
    if params[:commit] == 'Approve'
      leave_request.update(status: 'approved')
    else
      leave_request.update(status: 'rejected')
    end
    redirect_to leave_requests_path
  end
  

  private

  def all_employees
    @employees = Employee.all
  end

  def find_employee_leave_request
    @leave_request = LeaveRequest.find(params[:id])
  end

  def leave_params
    params.require(:leave_request).permit(:start_date, :end_date, :leave_type, :status, :employee_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendences_helper.rb
module AttendencesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/leave_requests_helper.rb
module LeaveRequestsHelper
end

app/views/attendences/_form.html.erb
<div class="row">
  <div class=" col-lg-3">
    <%= form_with model: @attendence do |form| %>
      <div class="field">
        <%= form.label :check_in_time%>
        <%= form.time_field :check_in_time , class:"form-control", placeholder:"Check in time" %>
      </div>
      <div class="field">
        <%= form.label :check_out_time %>
        <%= form.time_field :check_out_time,  class:"form-control", placeholder:"Check out time" %>
      </div>
      <div class="field">
        <%= form.label :date %>
        <%= form.date_field :date, class:"form-control", placeholder:"Date"%>
      </div>
      <div class="field">
        <%= form.collection_select :employee_id, @employees, :id, :first_name,  prompt: "Select a employee" %>
      </div>
      <div class="actions">
        <%= form.submit  %>
      </div>
    <% end %>
  </div>
</div>

app/views/attendences/edit.html.erb
<h1 class="p-3 mb-2 bg-dark text-white">Editing Leave Request of Employee</h1>

<%= render "form", attendence: @attendences %>

<br/>

<div>

    <%= link_to "Back to Attendence Table", attendences_path%>

app/views/attendences/index.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-info alert-dismissible" id="customAlert"><%= msg%>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<%end%>
<h1 class="p-3 mb-2 bg-dark text-white  ">Attendence Table</h1>
<h3 class="attendence bg-dark" ><%= link_to "Add Attendence of employee", new_attendence_path %></h3>
<table class="table table-bordered table-dark">
  <thead>
    <tr>
      <th scope="col">Employee</th>
      <th scope="col">Check in time</th>
      <th scope="col">Check out time</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
    <% @attendence.each do |attendence| %>
      <tr>
        <td><%= attendence.employee.first_name %>
          <td><%= attendence.check_in_time&.strftime("%I:%M %p") %></td>
          <td><%= attendence.check_out_time&.strftime("%I:%M %p") %></td>
          <td><%= attendence.date %></td>
        <td>
          <%= link_to "Delete", attendence_path(attendence), data: {"turbo-method": :delete, turbo_confirm: 'Are you sure?'}, class:"btn btn-outline-danger btn-sm" %>
          <%= link_to "Edit",   edit_attendence_path(attendence) %>
        </td>
        </tr> 
      <% end %>
    </tbody>
  </table>
  <script>  
    var closeButton = document.querySelector("#customAlert .close");


    var alertElement = document.getElementById("customAlert");


    closeButton.addEventListener("click", function() {

      alertElement.remove();
    });
  </script>

app/views/attendences/new.html.erb
<h1 class="p-3 mb-2 bg-dark text-white ">New employee</h1>

<%= render "form", attendence: @attendence %>

<br>

app/views/employees/_form.html.erb
<div class="row">
<div class=" col-lg-3">
<%= form_with model: @employee do |form| %>
  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name , class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field">
   <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field">
     <%= form.label :email %>
    <%= form.email_field :email, class:"form-control", placeholder:"Email"%>
  </div>

  <div class="field">
     <%= form.label :phone_num %>
    <%= form.number_field :phone_num, class:"form-control", placeholder:"Phone Number" %>
  </div>

  <div class="field">
   <%= form.label :hire_date%>
    <%= form.date_field :hire_date, class:"form-control", placeholder:"Hire Date" %>
  </div>

  <div class="field">
   <%= form.label :job_title %>
    <%= form.text_field :job_title, class:"form-control", placeholder:"Job Title" %>
  </div>

    <div class="field">
     <%= form.label :department %>
    <%= form.text_field :department, class:"form-control", placeholder:"Department" %>
  </div>
    
  <div class="actions">
    <%= form.submit  %>
  </div>
<% end %>
</div>
</div>

app/views/employees/edit.html.erb
<h1 class="p-3 mb-2 bg-dark text-white">Editing Employee</h1>

<%= render "form", employee: @employee %>

<br/>

<div>
    <%= link_to "Show this employee", @employee%> |
    <%= link_to "Back to employees", employees_path%>

app/views/employees/index.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-info alert-dismissible" id="customAlert"><%= msg%>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
<%end%>


<h1 class="p-3 mb-2 bg-dark text-white  ">Employees Table</h1>

<h3 class="add bg-dark" ><%= link_to "Add new employee", new_employee_path %></h3>

<table class="table table-bordered table-dark">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone number</th>
      <th scope="col">Hire Date</th>
      <th scope="col">Job Title</th>
      <th scope="col">Department</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @employee.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name%></td>
        <td><%= employee.email %></td>
        <td><%= employee.phone_num%></td>
        <td><%= employee.hire_date %></td>
        <td><%= employee.job_title %></td>
        <td><%= employee.department %></td>
        <td>
          <%= link_to "Show", employee_path(employee) %>
          <%= link_to "Delete", employee_path(employee), data: {"turbo-method": :delete, turbo_confirm: 'Are you sure?'}, class:"btn btn-outline-danger btn-sm" %>
          <%= link_to "Edit",   edit_employee_path(employee) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<script>

  var closeButton = document.querySelector("#customAlert .close");


  var alertElement = document.getElementById("customAlert");

  
  closeButton.addEventListener("click", function() {

    alertElement.remove();
  });
</script>

app/views/employees/new.html.erb
<h1 class="p-3 mb-2 bg-dark text-white ">New employee</h1>

<%= render "form", employee: @employee %>

<br>

app/views/employees/show.html.erb
<div class="show  ">
  
  <p>
    <span class="name">Name of the employee: </span>
    <span ><%= @employee.first_name%> <%= @employee.last_name%> </span> 
  </p>

  <p>
    <span class="name">Email: </span>
    <span><%= @employee.email%></span>
  </p>

 <p>
    <span class="name">Phone Number: </span>
    <span> <%= @employee.phone_num%> </span>
  </p>

 <p>
    <span class="name">Hire Date: </span>
    <span><%= @employee.hire_date%> </span>
  </p>

 <p>
    <span class="name">Job Title: </span>
    <span><%= @employee.job_title%></span>
  </p>

 <p>
    <span class="name">Department: </span>
    <span> <%= @employee.department%></span>
  </p>
 </div>


<div class="button">
  
  <button><%= link_to "Back to employees", employees_path %></button>
  
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to 'Employee Table', employees_path, class:"navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    
      <li class="nav-item">
      <%= link_to 'Leave Request',leave_requests_path, class:"nav-link"%>
      </li>

      <li class="nav-item">
      <%= link_to 'Attendence table',attendences_path, class:"nav-link"%>
      </li>

       
      <% if user_signed_in? %>

       <li class="nav-item">
        <%= link_to 'Sign out',destroy_user_session_path, data: {"turbo-method": :delete}, class:"nav-link"%>
        </li>
    
      <% else %>

       <li class="nav-item">
      <%= link_to 'Sign up',new_user_registration_path, class:"nav-link"%>
      </li>

      <li class="nav-item">
      <%= link_to 'Sign in',new_user_session_path, class:"nav-link"%>
      </li>

      <%end%>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hrms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
   
    <%= render 'layouts/header' %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/leave_requests/_form.html.erb
<div class="row">
  <div class=" col-lg-3">
    <%= form_with model: @leave_request do |form| %>
      <div class="field">
        <%= form.label :start_date %>
        <%= form.date_field :start_date , class:"form-control", placeholder:"Start date" %>
      </div>
      <div class="field">
      <%= form.label :end_date %>
        <%= form.date_field :end_date, class:"form-control", placeholder:"End Date" %>
      </div>
      <div class="field">
      <%= form.label :leave_type %>
        <%= form.text_field :leave_type, class:"form-control", placeholder:"Leave Type"%>
      </div>
      <div class="field">
        <%= form.collection_select :employee_id, @employees, :id, :first_name,  prompt: "Select a employee" %>
      </div>
      <div class="actions">
        <%= form.submit  %>
        </div>
      <% end %>
  </div>
</div>  

app/views/leave_requests/edit.html.erb
<h1 class="p-3 mb-2 bg-dark text-white">Editing Leave Request of Employee</h1>

<%= render "form", leave_request: @leave_requests %>

<br/>

<div>

    <%= link_to "Back to Leave Request Table", leave_requests_path%>

app/views/leave_requests/index.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-info alert-dismissible" id="customAlert"><%= msg%>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<%end%>
<h1 class="p-3 mb-2 bg-dark text-white  ">Leave Requests Table</h1>
<h3 class="add bg-dark" ><%= link_to "Add Leave Request", new_leave_request_path %></h3>
<table class="table table-bordered table-dark">
  <thead>
    <tr>
      <th scope="col">Employee</th>
      <th scope="col">Start Date</th>
      <th scope="col">End Date</th>
      <th scope="col">Leave Type</th>
      <th scope="col">Status</th>
      <th scope="col">Change Status</th>
    </tr>
  </thead>
  <tbody>
    <% @leave_request.each do |leave_request| %>
      <tr>
        <td><%= leave_request.employee.first_name%>
          <td><%= leave_request.start_date %></td>
          <td><%= leave_request.end_date%></td>
          <td><%= leave_request.leave_type %></td>
          <td><%= leave_request.status%></td>
          <td>
        <%= form_tag update_status_path(leave_request), method: :post do %>
          <%= submit_tag 'Approve', class: 'approve-button' %>
          <%= submit_tag 'Reject', class: 'reject-button' %>
        <% end %>
      </td>
      <td>
        <%= link_to "Delete", leave_request_path(leave_request), data: {"turbo-method": :delete, turbo_confirm: 'Are you sure?'}, class:"btn btn-outline-danger btn-sm" %>
        <%= link_to "Edit",   edit_leave_request_path(leave_request) %>
      </td>
    </tr>
  <% end %>
</tbody>
</table>
<script>
  var closeButton = document.querySelector("#customAlert .close");


  var alertElement = document.getElementById("customAlert");



  document.addEventListener("DOMContentLoaded", function() {
    // Get the form and buttons by their IDs
  var statusForm = document.getElementById("status-form");
  var tickButton = document.getElementById("tick-button");
  var crossButton = document.getElementById("cross-button");

  // Add click event listeners to the buttons
  tickButton.addEventListener("click", function() {
    // Set the value of the hidden input field (status) if needed
    console.log(tickButton.value);
    tickButton.value = "Approved";
    statusForm.submit(tickButton.value);
  });

  crossButton.addEventListener("click", function() {
    // Set the value of the hidden input field (status) if needed
    crossButton.value = "Rejected";
    statusForm.submit();
  });
    });
    // closeButton.addEventListener("click", function() {

    //   alertElement.remove();
    // });
</script>

app/views/leave_requests/new.html.erb
<h1 class="p-3 mb-2 bg-dark text-white ">New Leave request</h1>

<%= render "form", leave_request: @leave_request %>

<br>